#!/usr/bin/env bun

/**
 * Build-time generator: embeds all tool manifests as a TypeScript const.
 * Eliminates runtime filesystem scanning and import.meta.dir dependency.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ToolManifest } from './types.ts';

const TOOLS_DIR = path.join(import.meta.dir, 'tools');
const OUTPUT = path.join(import.meta.dir, 'manifests.generated.ts');

function scanManifests(): ToolManifest[] {
  const manifests: ToolManifest[] = [];

  for (const category of ['built-in', 'external']) {
    const categoryDir = path.join(TOOLS_DIR, category);
    if (!fs.existsSync(categoryDir)) continue;

    const entries = fs.readdirSync(categoryDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const manifestPath = path.join(categoryDir, entry.name, 'manifest.json');
      try {
        const raw = fs.readFileSync(manifestPath, 'utf-8');
        const parsed = JSON.parse(raw);
        if (parsed.name && typeof parsed.priority === 'number') {
          manifests.push(parsed);
        }
      } catch {
        // Skip invalid manifests
      }
    }
  }

  return manifests;
}

const manifests = scanManifests();
const output = `// Auto-generated by generate-manifests.ts -- do not edit manually
import type { ToolManifest } from './types.ts';

export const BUILT_IN_MANIFESTS: ToolManifest[] = ${JSON.stringify(manifests, null, 2)} as const;
`;

fs.writeFileSync(OUTPUT, output);
console.log(`[generate] ${manifests.length} tool manifests embedded in manifests.generated.ts`);
