// Auto-generated by generate-manifests.ts -- do not edit manually
import type { ToolManifest } from './types.ts';

export const BUILT_IN_MANIFESTS: ToolManifest[] = [
  {
    "name": "fs-tasks",
    "description": "Plain-file task backend (default, always available)",
    "binary": null,
    "detect": null,
    "provides": "tasks",
    "priority": 0,
    "adapter": "tools/built-in/fs-tasks/adapter.ts"
  },
  {
    "name": "fs-search",
    "description": "Filesystem session search (built-in fallback)",
    "binary": null,
    "detect": null,
    "transport": "builtin",
    "provides": "search",
    "priority": 0,
    "adapter": "tools/built-in/fs-search/adapter.ts",
    "inject": [
      "projectRoot"
    ]
  },
  {
    "name": "fs-handoff",
    "description": "Filesystem handoff adapter (built-in fallback)",
    "binary": null,
    "detect": null,
    "transport": "builtin",
    "provides": "handoff",
    "priority": 0,
    "adapter": "tools/built-in/fs-handoff/adapter.ts",
    "inject": [
      "projectRoot",
      "taskPort",
      "memoryPort"
    ]
  },
  {
    "name": "bv",
    "transport": "cli",
    "description": "Beads Visualizer for task dependency graphs and insights",
    "binary": "bv",
    "detect": "bv --version",
    "install": "cargo install beads_viz",
    "homepage": "https://github.com/user/beads_viz",
    "provides": "graph",
    "priority": 100,
    "adapter": "tools/external/bv/adapter.ts"
  },
  {
    "name": "cass",
    "transport": "cli",
    "description": "Code-aware semantic search for session and context retrieval",
    "binary": "cass",
    "detect": "cass --version",
    "install": "cargo install cass",
    "homepage": "https://github.com/user/cass",
    "provides": "search",
    "priority": 100,
    "adapter": "tools/external/cass/adapter.ts"
  },
  {
    "name": "agent-mail",
    "transport": "http",
    "baseUrl": "http://localhost:8765",
    "description": "Agent Mail handoff protocol for inter-agent task delegation",
    "binary": null,
    "detect": null,
    "provides": "handoff",
    "priority": 100,
    "adapter": "tools/external/agent-mail/adapter.ts",
    "inject": [
      "projectRoot",
      "taskPort",
      "memoryPort",
      "configPort"
    ]
  },
  {
    "name": "mcp-search",
    "transport": "mcp-stdio",
    "command": "npx",
    "args": [
      "-y",
      "@example/mcp-search"
    ],
    "description": "Session search via MCP server (example bridge adapter)",
    "binary": null,
    "detect": null,
    "provides": "search",
    "priority": 80,
    "adapter": "tools/external/mcp-search/adapter.ts"
  },
  {
    "name": "br",
    "transport": "cli",
    "description": "Beads Rust task backend with sync, graph queries, and batch ops",
    "binary": "br",
    "detect": "br --version",
    "install": "cargo install beads_rust",
    "homepage": "https://github.com/user/beads_rust",
    "provides": "tasks",
    "priority": 100,
    "adapter": "tools/external/br/adapter.ts"
  },
  {
    "name": "mcp-graph",
    "transport": "mcp-stdio",
    "command": "npx",
    "args": [
      "-y",
      "@example/mcp-graph"
    ],
    "description": "Task dependency graph via MCP server (example bridge adapter)",
    "binary": null,
    "detect": null,
    "provides": "graph",
    "priority": 80,
    "adapter": "tools/external/mcp-graph/adapter.ts"
  }
] as const;
