#!/usr/bin/env bun
// Build-time generator: reads skills/built-in/[name]/SKILL.md frontmatter + content
// and emits src/skills/registry.generated.ts with embedded skill content

import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { parseFrontmatterRich } from '../../infra/utils/frontmatter.ts';

const ROOT = join(import.meta.dir, '..', '..', '..');
const SKILLS_DIR = join(ROOT, 'skills', 'built-in');
const OUT_FILE = join(ROOT, 'src', 'app', 'skills', 'registry.generated.ts');

interface SkillMeta {
  slug: string;
  description: string;
  content: string;
  argumentHint?: string;
  stage?: string[];
  audience?: string;
  references: Record<string, string>;
}

/**
 * Recursively scan a reference/ directory and collect all files as path->content pairs.
 * Files inside reference/ are opaque content -- do NOT parse SKILL.md as skill definitions.
 */
async function scanReferences(refDir: string, basePath: string = ''): Promise<Record<string, string>> {
  const refs: Record<string, string> = {};
  let entries;
  try {
    entries = await readdir(refDir, { withFileTypes: true });
  } catch {
    return refs; // no reference/ directory -- return empty
  }

  for (const entry of entries) {
    const entryPath = join(refDir, entry.name);
    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      const nested = await scanReferences(entryPath, relativePath);
      Object.assign(refs, nested);
    } else if (entry.isFile()) {
      refs[relativePath] = await readFile(entryPath, 'utf-8');
    }
  }

  return refs;
}

async function main() {
  const dirEntries = await readdir(SKILLS_DIR, { withFileTypes: true });
  const dirs = dirEntries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

  const skills: SkillMeta[] = [];

  for (const slug of dirs) {
    const mdPath = join(SKILLS_DIR, slug, 'SKILL.md');
    let raw: string;
    try {
      raw = await readFile(mdPath, 'utf-8');
    } catch {
      console.warn(`[!] Skipping ${slug}: no SKILL.md`);
      continue;
    }

    const fm = parseFrontmatterRich(raw);
    if (!fm?.name || !fm?.description) {
      console.warn(`[!] Skipping ${slug}: missing name or description in frontmatter`);
      continue;
    }

    // Parse stage: string -> [string], string[] -> string[], absent -> undefined
    let stage: string[] | undefined;
    if (fm.stage) {
      stage = Array.isArray(fm.stage) ? fm.stage.map(String) : [String(fm.stage)];
    }

    const refDir = join(SKILLS_DIR, slug, 'reference');
    const references = await scanReferences(refDir);

    const audience = fm.audience ? String(fm.audience) : undefined;

    skills.push({
      slug,
      description: String(fm.description),
      content: raw,
      argumentHint: fm['argument-hint'] ? String(fm['argument-hint']) : undefined,
      stage,
      audience,
      references,
    });
  }

  const names = skills.map((s) => `'${s.slug}'`).join(', ');

  const entries = skills
    .map((s) => {
      const parts = [
        `description: ${JSON.stringify(s.description)}`,
        `content: ${JSON.stringify(s.content)}`,
      ];
      if (s.argumentHint) {
        parts.push(`argumentHint: ${JSON.stringify(s.argumentHint)}`);
      }
      if (s.stage) {
        parts.push(`stage: ${JSON.stringify(s.stage)}`);
      }
      if (s.audience) {
        parts.push(`audience: ${JSON.stringify(s.audience)}`);
      }
      if (Object.keys(s.references).length > 0) {
        parts.push(`references: ${JSON.stringify(s.references)}`);
      }
      return `  '${s.slug}': { ${parts.join(', ')} },`;
    })
    .join('\n');

  const code = `// Auto-generated by src/skills/generate.ts -- do not edit
export const BUILTIN_SKILL_NAMES = [${names}] as const;
export type BuiltinSkillName = typeof BUILTIN_SKILL_NAMES[number];
export const BUILTIN_SKILLS: Record<BuiltinSkillName, { description: string; content: string; argumentHint?: string; stage?: string[]; audience?: string; references?: Record<string, string> }> = {
${entries}
};
`;

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(`[ok] Generated ${OUT_FILE} with ${skills.length} skills`);
}

main().catch((err) => {
  console.error('[!] generate.ts failed:', err);
  process.exit(1);
});
