#!/usr/bin/env bun

/**
 * Build-time generator: embeds agent tool manifests, guidance docs, and protocols.
 * Eliminates runtime filesystem scanning and import.meta.dir dependency.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AgentToolManifest } from './types.ts';

const BASE_DIR = import.meta.dir;
const BUILT_IN_DIR = path.join(BASE_DIR, 'built-in');
const PROTOCOLS_DIR = path.join(BASE_DIR, 'protocols');
const OUTPUT = path.join(BASE_DIR, 'agent-data.generated.ts');

function scanManifests(): AgentToolManifest[] {
  const manifests: AgentToolManifest[] = [];
  if (!fs.existsSync(BUILT_IN_DIR)) return manifests;

  for (const entry of fs.readdirSync(BUILT_IN_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifestPath = path.join(BUILT_IN_DIR, entry.name, 'manifest.json');
    try {
      const parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
      if (parsed.name && parsed.binary && parsed.detect) {
        manifests.push(parsed);
      }
    } catch { /* skip */ }
  }
  return manifests;
}

function scanGuidance(): Record<string, string> {
  const guidance: Record<string, string> = {};
  if (!fs.existsSync(BUILT_IN_DIR)) return guidance;

  for (const entry of fs.readdirSync(BUILT_IN_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const guidancePath = path.join(BUILT_IN_DIR, entry.name, 'guidance.md');
    try {
      guidance[entry.name] = fs.readFileSync(guidancePath, 'utf-8');
    } catch { /* no guidance for this tool */ }
  }
  return guidance;
}

function scanProtocols(): Record<string, string> {
  const protocols: Record<string, string> = {};
  if (!fs.existsSync(PROTOCOLS_DIR)) return protocols;

  for (const entry of fs.readdirSync(PROTOCOLS_DIR, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const name = entry.name.replace(/\.md$/, '');
    protocols[name] = fs.readFileSync(path.join(PROTOCOLS_DIR, entry.name), 'utf-8');
  }
  return protocols;
}

const manifests = scanManifests();
const guidance = scanGuidance();
const protocols = scanProtocols();

const output = `// Auto-generated by generate-agent-data.ts -- do not edit manually
import type { AgentToolManifest } from './types.ts';

export const AGENT_TOOL_MANIFESTS: AgentToolManifest[] = ${JSON.stringify(manifests, null, 2)} as const;

export const AGENT_GUIDANCE: Record<string, string> = ${JSON.stringify(guidance, null, 2)};

export const AGENT_PROTOCOLS: Record<string, string> = ${JSON.stringify(protocols, null, 2)};
`;

fs.writeFileSync(OUTPUT, output);
console.log(`[generate] ${manifests.length} agent manifests, ${Object.keys(guidance).length} guidance docs, ${Object.keys(protocols).length} protocols embedded`);
