import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { execFile } from 'child_process';
import { writeAtomic, ensureDir } from '../utils/fs-io.ts';
import { MAESTRO_CSS, GOOGLE_FONTS_LINK } from './css.ts';
import type { VisualType, VisualResult } from '../../app/visual/types.ts';

const VISUALS_DIR = path.join(os.homedir(), '.maestro', 'visuals');
const VISUALS_MAX_FILES = 100;

// ============================================================================
// Filename Generation
// ============================================================================

function sanitizeForFilename(s: string): string {
  return s.replace(/[^a-zA-Z0-9._-]/g, '-').replace(/-{2,}/g, '-').replace(/^-|-$/g, '');
}

export function buildFilename(type: VisualType, feature?: string): string {
  const now = new Date();
  const ts = now.toISOString().replace(/[:.]/g, '-').slice(0, 23);
  const suffix = Math.random().toString(36).slice(2, 10);
  const parts: string[] = [type];
  if (feature) parts.push(sanitizeForFilename(feature));
  parts.push(ts);
  parts.push(suffix);
  return `${parts.join('-')}.html`;
}

// ============================================================================
// HTML Escaping & Sanitization
// ============================================================================

const HTML_ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/** Escape HTML special characters. Use for ALL dynamic content in HTML context. */
export function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (ch) => HTML_ESCAPE_MAP[ch] ?? ch);
}

/** JSON.stringify with circular reference protection. */
export function safeStringify(value: unknown, indent = 2): string {
  try {
    return JSON.stringify(value, null, indent);
  } catch {
    return '[non-serializable data]';
  }
}

/**
 * Sanitize text for use in Mermaid diagram labels and node IDs.
 * Separate from escapeHtml -- Mermaid's parser breaks on different characters
 * (spaces, dots, colons, brackets, newlines, etc.) even when HTML-safe.
 * Uses a whitelist: only alphanumeric, underscore, and hyphen survive.
 */
export function sanitizeMermaidLabel(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, '-').replace(/-{2,}/g, '-').replace(/^-|-$/g, '') || 'unnamed';
}

// ============================================================================
// Page Rendering
// ============================================================================

export interface PageOptions {
  title: string;
  bodyHtml: string;
  extraHead?: string;
  extraScripts?: string;
}

export function renderPage(opts: PageOptions): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(opts.title)}</title>
  ${GOOGLE_FONTS_LINK}
  <style>${MAESTRO_CSS}</style>
  ${opts.extraHead ?? ''}
</head>
<body>
  <div class="container">
    ${opts.bodyHtml}
  </div>
  ${opts.extraScripts ? `<script>${opts.extraScripts}</script>` : ''}
  <div class="container"><div class="footer">Generated by maestro at ${new Date().toISOString()}</div></div>
</body>
</html>`;
}

// ============================================================================
// File Rotation
// ============================================================================

function rotateOldFiles(): void {
  try {
    const files = fs.readdirSync(VISUALS_DIR).filter(f => f.endsWith('.html'));
    if (files.length <= VISUALS_MAX_FILES) return;

    const withStats = files.map(f => {
      const fullPath = path.join(VISUALS_DIR, f);
      try {
        const stat = fs.statSync(fullPath);
        return { path: fullPath, birthtimeMs: stat.birthtimeMs };
      } catch {
        return null;
      }
    }).filter((x): x is { path: string; birthtimeMs: number } => x !== null);

    // Sort newest first, keep first (MAX - 20), delete the rest
    withStats.sort((a, b) => b.birthtimeMs - a.birthtimeMs);
    const toKeep = VISUALS_MAX_FILES - 20;
    const toDelete = withStats.slice(toKeep);

    for (const entry of toDelete) {
      try {
        fs.unlinkSync(entry.path);
      } catch {
        // ENOENT from concurrent rotation -- ignore
      }
    }
  } catch {
    // Directory may not exist yet -- ignore
  }
}

// ============================================================================
// Browser Opening
// ============================================================================

function openBrowser(filePath: string): Promise<boolean> {
  return new Promise((resolve) => {
    const platform = process.platform;

    if (platform === 'linux') {
      const hasDisplay = process.env.DISPLAY || process.env.WAYLAND_DISPLAY;
      if (!hasDisplay) {
        resolve(false);
        return;
      }
    }

    let cmd: string;
    let args: string[];

    if (platform === 'darwin') {
      cmd = 'open';
      args = [filePath];
    } else if (platform === 'win32') {
      cmd = 'cmd';
      args = ['/c', 'start', filePath];
    } else {
      cmd = 'xdg-open';
      args = [filePath];
    }

    try {
      const child = execFile(cmd, args);
      child.on('error', () => resolve(false));
      child.on('exit', (code) => resolve(code === 0));
    } catch {
      resolve(false);
    }
  });
}

// ============================================================================
// Write Visual
// ============================================================================

export async function writeVisual(
  type: VisualType,
  html: string,
  feature?: string,
  autoOpen: boolean = true,
): Promise<VisualResult> {
  ensureDir(VISUALS_DIR);
  rotateOldFiles();

  const filename = buildFilename(type, feature);
  const filePath = path.join(VISUALS_DIR, filename);
  writeAtomic(filePath, html);

  let opened = false;
  if (autoOpen) {
    opened = await openBrowser(filePath);
  }

  return { path: filePath, opened, type, feature };
}

export function getVisualsDir(): string {
  return VISUALS_DIR;
}
